defaults:
  - model: hpt_bc_so100_singlearm_joint_base
  - visualization: so100_singlearm
  - paths: default
  - trainer: default
  - logger: debug
  - data: so100_singlearm_joint
  - callbacks: checkpoints
  - data_schematic: so100_singlearm_joint
  - override hydra/launcher: basic
  - _self_

name: so100_hpt
description: hpt_fm_so100_only_joint_gripper5x_steps60k
ckpt_path: null
mode: train

hydra:
  run:
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./logs/${name}/${description}_${now:%Y-%m-%d_%H-%M-%S}

seed: 42
reject_outliers: false
evaluator: null

model:
  robomimic_model:
    head_specs:
      so100_singlearm:
        action_dim_loss_weights: [1, 1, 1, 1, 1, 5]
        normalize_action_dim_loss_weights: true
  scheduler:
    T_max: 60000

trainer:
  default_root_dir: ${hydra:runtime.output_dir}
  accelerator: gpu
  devices: 1
  precision: bf16
  max_epochs: -1
  min_epochs: 0
  max_steps: 60000
  min_steps: 0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  deterministic: false

data:
  train_datasets:
    so100_singlearm:
      mode: train
      valid_ratio: 0.1
  valid_datasets:
    so100_singlearm:
      mode: valid
      valid_ratio: 0.1
  train_dataloader_params:
    so100_singlearm:
      batch_size: 32
      num_workers: 8
  valid_dataloader_params:
    so100_singlearm:
      batch_size: 32
      num_workers: 4

logger:
  csv:
    _target_: lightning.pytorch.loggers.CSVLogger
    save_dir: ${paths.output_dir}
    name: csv

callbacks:
  model_checkpoint:
    filename: step_{step}
    auto_insert_metric_name: false
    save_top_k: -1
    save_last: true
    every_n_train_steps: 5000
    every_n_epochs: null

norm_stats:
  sample_frac: 1.0
  num_workers: 4
  save_cache_dir: ${hydra:runtime.output_dir}
  precomputed_norm_path: null
