_target_: egomimic.pl_utils.pl_model.ModelWrapper
robomimic_model:
  _target_: egomimic.algo.hpt.HPT
  data_schematic: _${data.dataset.data_schematic}
  camera_transforms: {}

  diffusion: false
  6dof: true

  ac_keys:
    so100_singlearm: "actions_cartesian"

  trunk:
    embed_dim: 256
    num_blocks: 16
    num_heads: 8
    token_postprocessing: "action_token"
    observation_horizon: 1
    action_horizon: 64
    no_trunk: false
    use_domain_embedding: true
    drop_path: 0.1
    weight_init_style: "pytorch"

  multitask: false
  pretrained: false
  pretrained_checkpoint: ""
  reverse_kl_samples: 0

  domains: ["so100_singlearm"]
  shared_obs_keys: ["front_img_1"]

  shared_stem_specs:
    front_img_1:
      _target_: egomimic.models.hpt_nets.MLPPolicyStem
      input_dim: 256
      output_dim: 256
      widths: [256]
      specs:
        random_horizon_masking: false
        cross_attn:
          crossattn_latent: 16
          crossattn_heads: 8
          crossattn_dim_head: 64
          crossattn_modality_dropout: 0.1
          modality_embed_dim: 256

  stem_specs:
    so100_singlearm:
      state_ee_pose:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 7
        output_dim: 256
        widths: [256]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 256

  head_specs:
    so100_singlearm:
      _target_: egomimic.models.hpt_nets.MLPPolicyHead
      input_dim: 256
      output_dim: 7
      widths: [256]

  encoder_specs:
    front_img_1:
      _target_: egomimic.models.hpt_nets.ResNet
      output_dim: 256
      resnet_model: resnet18
      weights: DEFAULT

  train_image_augs:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
        hue: 0.05
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  eval_image_augs:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3e-4
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 100000
  eta_min: 1e-5
